#Un docker compose commence toujours par dire sous quel version de docker_compose il va
#fonctionner
version : "3.9"

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        env_file: .env
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p$MARIADB_PASSWORD"]
            interval: 30s
            timeout: 30s
            retries: 5
        network: 
            - inception_ntw
        ports:
            - 3306:3306
        restart: unless-stopped
        volumes:
            - mariadb-volume:/var/lib/mysql

#Par défaut le réseau est créé par compose mais on le précise pour le sujet
networks:
    inception_ntw:

volumes:
    mariadb-volume:
    driver: local
    driver_opts:
        type: volume 
        device: /home/ybrutout/data/mariadb
        o: bind

