#Un docker compose commence toujours par dire sous quel version de docker_compose il va
#fonctionner
version : "3.9"

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        env_file: .env
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p$MARIADB_PWD"]
            interval: 30s
            timeout: 30s
            retries: 5
        networks: 
            - inception_ntw
        ports:
           - "3306:3306"
        restart: unless-stopped
        volumes:
            - mariadb-volume:/var/lib/mysql
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        depends_on:
            mariadb :
                condition: service_healthy
        env_file: .env
        networks:
            - inception_ntw
        ports:
            - "9000:9000"
        restart: unless-stopped
        volumes:
            - wordpress-volume:/var/www/wordpress
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        depends_on:
            - wordpress
        networks:
            - inception_ntw
        ports:
            - "443:443"
        restart: unless-stopped
        volumes:
            - wordpress-volume:/var/www/wordpress



#Par défaut le réseau est créé par compose mais on le précise pour le sujet
networks:
    inception_ntw:

volumes:
    mariadb-volume:
        driver: local
        driver_opts:
            device: /home/ybrutout/data/mariadb
            type: volume
            o: bind
    wordpress-volume:
        driver: local
        driver_opts:
            device: /home/ybrutout/data/wordpress
            type: volume
            o: bind
